// ─────────────────────────────────────────────────────────────────────────────
// Agent identities module — governance Phase 5 (provision)
//
// Provisions one User-Assigned Managed Identity per registered agent. Today a
// UAMI is the concrete Azure primitive that backs an "agent identity"; as the
// Entra Agent ID control plane becomes generally available these identities map
// 1:1 to registered agents.
//
// The `agents` array MUST mirror governance/agent-registry.yaml
// (entra.identity_name). It is GENERATED by governance/generate_bicep_params.py
// (-> infra/params/agent365.params.json) and kept in lockstep in CI.
//
// This module ONLY creates identities. Least-privilege role assignments are
// applied separately (see infra/modules/agent-rbac.bicep) so identity creation
// and authorization stay auditable and independently reviewable.
// ─────────────────────────────────────────────────────────────────────────────

@description('Azure region for the managed identities.')
param location string = resourceGroup().location

@description('Resource tags applied to every identity.')
param tags object = {}

@description('''
Registered agents to provision identities for. Each entry mirrors an agent in
governance/agent-registry.yaml:
  - id:           the registry agent id (e.g. lisa-voice-avatar)
  - identityName: entra.identity_name (e.g. id-tva-lisa)
''')
param agents array

resource agentIdentities 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = [
  for agent in agents: {
    name: agent.identityName
    location: location
    tags: union(tags, {
      'agent-id': agent.id
      'governed-by': 'agent-registry'
      purpose: 'agent-identity'
    })
  }
]

@description('Per-agent identity outputs (id, principalId, clientId) for downstream RBAC.')
output identities array = [
  for (agent, i) in agents: {
    id: agent.id
    identityName: agent.identityName
    resourceId: agentIdentities[i].id
    principalId: agentIdentities[i].properties.principalId
    clientId: agentIdentities[i].properties.clientId
  }
]
